import requests
from utils.logger import Logger

log = Logger("WAFBypass")

WAF_SIGNATURES = {
    "Cloudflare": ["cf-ray", "__cfduid"],
    "AWS WAF": ["x-amzn-RequestId", "aws-waf-token"],
    "ModSecurity": ["Mod_Security", "This error was generated by Mod_Security"],
    "Wordfence": ["Generated by Wordfence"],
}

def detect_waf(url):
    try:
        r = requests.get(url, timeout=5)
        headers = str(r.headers).lower()
        content = r.text.lower()
        for waf, signs in WAF_SIGNATURES.items():
            for sign in signs:
                if sign.lower() in headers or sign.lower() in content:
                    return waf
    except:
        pass
    return None

def test(url):
    waf = detect_waf(url)
    if waf:
        log.info(f"Detected WAF: {waf}")
    else:
        log.info("No WAF detected")
    return waf
